package exerciseExceptionHandling;

public class RuntimeExceptionError {
public static void main(String[] args) {
	int a =0;
	try {
		double div = 9/a;
		System.out.println("division is"+ div);
	} catch (RuntimeException e) {
		
	}catch (ArithmeticException i) {
		
	}
	//RuntimeException
	
}
}

